# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    curl -fsSL https://cli.fluentci.io | bash
    fluentci --version
    echo "##vso[task.prependpath]${HOME}/.deno/bin"
  displayName: 'Setup FluentCI'

- script: |
    fluentci run --wasm bun install
    fluentci run --wasm bun test
  displayName: 'bun install and test'

- script: |
    fluentci run --wasm bun run build
  displayName: 'Run build'
